version: '3.8'

services:
  at-extender:
    image: ghcr.io/dinobeiser/at-extender:latest
    container_name: at-extender
    restart: unless-stopped
    
    # Use Docker secrets for sensitive data
    secrets:
      - at_extender_rufnummer
      - at_extender_passwort
      - at_extender_bot_token
      - at_extender_chat_id
    
    environment:
      # Non-sensitive configuration
      - TELEGRAM=1
      - AUTO_UPDATE=1
      - SLEEP_MODE=smart
      - BROWSER=chromium
    
    volumes:
      - at_extender_data:/app/data
    
    user: "1000:1000"
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  at_extender_data:
    driver: local

secrets:
  at_extender_rufnummer:
    file: ./secrets/rufnummer.txt
  at_extender_passwort:
    file: ./secrets/passwort.txt
  at_extender_bot_token:
    file: ./secrets/bot_token.txt
  at_extender_chat_id:
    file: ./secrets/chat_id.txt
